import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.events': 'Events',
    'nav.workouts': 'Workouts',
    'nav.calculator': 'Calculator',
    'nav.support': 'Anonymous Support Groups',
    
    // Home page
    'home.hero.title': 'Your Journey to Better Health Starts Here',
    'home.hero.subtitle': 'Join our community dedicated to promoting good health and wellbeing',
    'home.hero.viewWorkouts': 'View Workouts',
    'home.hero.checkBMI': 'Check Your BMI',
    'home.features.title': 'Why Choose PROACTIVE?',
    'home.features.events.title': 'Find Events',
    'home.features.events.desc': 'Join health and fitness events',
    'home.features.bmi.title': 'BMI Calculator',
    'home.features.bmi.desc': 'Track your health metrics and understand your body better',
    'home.features.workouts.title': 'Workouts',
    'home.features.workouts.desc': 'Transform your fitness with our designed workouts',
    'home.features.advocacy.title': 'Health & Wellbeing',
    'home.features.advocacy.desc': 'Empowering you with knowledge for a healthier lifestyle',
    'home.blog.title': 'Health & Wellbeing',
    'home.blog.subtitle': 'Discover tips and facts to improve your daily life',
    'home.blog.readMore': 'Read more',
    'home.newsletter.title': 'Stay Updated',
    'home.newsletter.desc': 'Subscribe to receive health tips and updates',
    'home.newsletter.placeholder': 'Enter your email',
    'home.newsletter.button': 'Subscribe',
    'home.newsletter.success': 'Successfully subscribed to newsletter!',
    'home.cta.title': 'Ready to Start Your Health Journey?',
    'home.cta.subtitle': 'Join thousands of people who are already improving their health with PROACTIVE',
    'home.cta.bmi': 'Calculate Your BMI',
    'home.cta.workouts': 'Start Working Out',

    // Did You Know Posts
    'didyouknow.title': 'Did You Know?',
    'didyouknow.subtitle': 'Discover interesting health facts and tips to improve your daily life',
    'didyouknow.hydration.title': 'Stay Hydrated',
    'didyouknow.hydration.content': 'Lack of hydration can lead to tiredness and reduced energy. Staying adequately hydrated can boost energy and enhance mental performance.',
    'didyouknow.sleep.title': 'Quality Sleep Matters',
    'didyouknow.sleep.content': 'Getting 7-9 hours of quality sleep each night can improve memory and boost immune function.',
    'didyouknow.share': 'Share',
    'didyouknow.imageDownloaded': 'Image downloaded!',
    'didyouknow.shareDescription': 'Share it on your favorite social media platform.',
    
    // Events page
    'events.hero.title': 'Health & Fitness Events',
    'events.hero.subtitle': 'Join our community events and take your wellness journey to the next level',
    'events.title': 'Bicycle City Marathon',
    'events.description': 'Join us for the Bicycle City Marathon! The race starts from Maputo Shopping Centre to Tchumene Circular and back. Free for participants with their own bicycle and helmet. 200 Meticals for those who need bicycle and helmet rental.',
    'events.date': '12 December 2026',
    'events.location': 'R. Ngungunhane, Maputo',
    'events.register': 'Register Now',
    'events.viewGallery': 'View Gallery',
    'events.addImage': 'Add Image',
    'events.enterPassword': 'Enter admin password',
    'events.imageUrl': 'Image URL',
    'events.uploadImage': 'Upload from Device',
    'events.orUpload': 'Or upload from your device',
    'events.add': 'Add',
    'events.wrongPassword': 'Incorrect password',
    'events.imageAdded': 'Image added successfully',
    'events.noImages': 'No images in the gallery yet. Add some photos!',
    'events.notActive': 'Not Active',
    
    // Workouts page
    'workouts.hero.title': 'Workouts',
    'workouts.hero.subtitle': 'Transform your fitness with our designed workouts',
    'workouts.tabs.library': 'Exercise Library',
    'workouts.tabs.generator': 'Create Workout Plan',
    'workouts.tabs.plan': 'My Plan',
    'workouts.filters.type': 'Type',
    'workouts.filters.equipment': 'Equipment',
    'workouts.filters.muscle': 'Muscle',
    'workouts.filters.allTypes': 'All Types',
    'workouts.filters.allEquipment': 'All Equipment',
    'workouts.filters.allMuscles': 'All Muscles',
    'workouts.types.strength': 'Strength',
    'workouts.types.cardio': 'Cardio',
    'workouts.types.stretching': 'Stretching',
    'workouts.equipment.bodyweight': 'Body Weight',
    'workouts.equipment.barbell': 'Barbell',
    'workouts.equipment.dumbbells': 'Dumbbells',
    'workouts.equipment.bench': 'Bench',
    'workouts.equipment.stabilityball': 'Stability Ball',
    'workouts.equipment.cable': 'Cable Machine',
    'workouts.equipment.machine': 'Machine',
    'workouts.muscles.chest': 'Chest',
    'workouts.muscles.triceps': 'Triceps',
    'workouts.muscles.shoulders': 'Shoulders',
    'workouts.muscles.core': 'Core',
    'workouts.muscles.abs': 'Abs',
    'workouts.muscles.back': 'Back',
    'workouts.howTo': 'How to do it:',
    'workouts.noResults': 'No exercises found matching your filters.',
    'workouts.clickFullscreen': 'Click to view fullscreen',

    // Exercise names and instructions
    'exercise.barbellFrontRaises.name': 'Barbell Front Raises',
    'exercise.barbellFrontRaises.howTo': 'Stand with your feet shoulder-width apart, holding a barbell in front of your thighs with an overhand grip. Keep your arms straight and lift the barbell up to shoulder height, pause briefly, then slowly lower it back down. Focus on controlled movements and avoid swinging.',
    'exercise.arnoldPress.name': 'Arnold Press',
    'exercise.arnoldPress.howTo': 'Start seated with dumbbells at shoulder height, palms facing you. As you press the weights overhead, rotate your palms to face forward at the top. Reverse the motion as you lower the weights back down. This works your shoulders through a fuller range of motion.',
    'exercise.barbellUprightRows.name': 'Barbell Upright Rows',
    'exercise.barbellUprightRows.howTo': 'Hold a barbell with a narrow grip in front of your thighs. Pull the bar straight up along your body until it reaches chest level, keeping your elbows pointing outward. Lower the bar slowly and repeat. Keep your core engaged throughout.',
    'exercise.backExtension.name': 'Back Extension on Stability Ball',
    'exercise.backExtension.howTo': 'Lie face down on a stability ball with your hips on the ball and feet anchored against a wall or floor. Place hands behind your head. Lower your upper body towards the floor, then lift up by engaging your lower back muscles. Keep movements controlled and avoid hyperextending.',
    'exercise.barbellShrugs.name': 'Barbell Shrugs',
    'exercise.barbellShrugs.howTo': 'Stand with feet shoulder-width apart, holding a barbell with an overhand grip in front of your thighs. Keep arms straight and raise your shoulders up towards your ears as high as possible. Hold briefly at the top, then lower slowly. Keep your core tight and avoid rolling shoulders.',
    'exercise.benchDips.name': 'Bench Dips',
    'exercise.benchDips.howTo': 'Place your hands on a bench behind you with fingers facing forward. Extend your legs out in front. Lower your body by bending your elbows until upper arms are parallel to the floor. Push back up to the starting position. Keep your back close to the bench throughout.',
    'exercise.benchPress.name': 'Bench Press',
    'exercise.benchPress.howTo': 'Lie on a flat bench with feet flat on the floor. Grip the barbell slightly wider than shoulder-width. Lower the bar slowly to your mid-chest, pause briefly, then press back up to the starting position. Keep your core tight and maintain a slight arch in your lower back.',
    'exercise.bentArmPullover.name': 'Bent Arm Pullover',
    'exercise.bentArmPullover.howTo': 'Lie on a bench with only your upper back supported. Hold a barbell with arms bent at 90 degrees. Lower the weight behind your head in an arc, feeling a stretch in your lats. Pull the weight back to the starting position using your chest and lats.',
    'exercise.bentKneeHipRaise.name': 'Bent Knee Hip Raise',
    'exercise.bentKneeHipRaise.howTo': 'Lie on your back with arms at your sides and knees bent at 90 degrees. Lift your hips off the ground by contracting your abs and bringing your knees towards your chest. Lower back down with control. Focus on using your lower abs, not momentum.',
    'exercise.bicepCurlsBarbell.name': 'Bicep Curls (Barbell)',
    'exercise.bicepCurlsBarbell.howTo': 'Stand with feet shoulder-width apart, holding a barbell with an underhand grip. Keep elbows close to your sides. Curl the bar up towards your shoulders, squeezing your biceps at the top. Lower slowly back to the starting position. Avoid swinging or using momentum.',
    'exercise.hammerCurl.name': 'Hammer Curl',
    'exercise.hammerCurl.howTo': 'Stand with feet hip-width apart, holding dumbbells at your sides with palms facing inward (neutral grip). Curl the weights up towards your shoulders, keeping the neutral grip throughout. Lower slowly and repeat. This targets both the biceps and forearms.',
    'exercise.bicepsCurlDumbbell.name': 'Biceps Curl (Dumbbell)',
    'exercise.bicepsCurlDumbbell.howTo': 'Stand holding dumbbells at your sides with palms facing forward. Curl both weights up towards your shoulders while keeping elbows stationary. Squeeze at the top, then lower under control. You can alternate arms or curl both simultaneously.',
    'exercise.dumbbellFlys.name': 'Dumbbell Flys',
    'exercise.dumbbellFlys.howTo': 'Lie on a flat bench with a dumbbell in each hand. Start with arms extended above your chest, palms facing each other. Lower the weights out to the sides in an arc until you feel a stretch in your chest. Squeeze your chest muscles to bring the weights back together.',
    'exercise.dumbbellFrontRaises.name': 'Dumbbell Front Raises',
    'exercise.dumbbellFrontRaises.howTo': 'Stand with feet shoulder-width apart, holding a dumbbell in each hand at your thighs. Keep arms straight and raise the weights in front of you to shoulder height. Lower slowly and repeat. Focus on controlled movements.',
    'exercise.bicepsCurlReverse.name': 'Reverse Biceps Curl',
    'exercise.bicepsCurlReverse.howTo': 'Stand with dumbbells at your sides, palms facing backward (overhand grip). Curl the weights up towards your shoulders while maintaining the overhand grip. Lower with control. This variation targets the forearms and brachialis.',
    'exercise.bridge.name': 'Bridge',
    'exercise.bridge.howTo': 'Lie on your back with knees bent and feet flat on the floor. Push through your heels to lift your hips off the ground until your body forms a straight line from shoulders to knees. Squeeze your glutes at the top, then lower slowly.',
    'exercise.concentrationCurls.name': 'Concentration Curls',
    'exercise.concentrationCurls.howTo': 'Sit on a bench with legs spread. Rest your elbow against the inside of your thigh while holding a dumbbell. Curl the weight up towards your shoulder, focusing on squeezing the bicep. Lower slowly and repeat.',
    'exercise.crossBodyCrunch.name': 'Cross Body Crunch',
    'exercise.crossBodyCrunch.howTo': 'Lie on your back with hands behind your head and knees bent. Lift your shoulder blades off the ground and twist to bring your right elbow towards your left knee. Return and repeat on the other side. Focus on the twisting motion.',
    'exercise.crunches.name': 'Crunches',
    'exercise.crunches.howTo': 'Lie on your back with knees bent and hands behind your head. Engage your core and lift your shoulder blades off the floor. Hold briefly at the top, then lower back down with control. Avoid pulling on your neck.',
    'exercise.crunchesWithStabilityBall.name': 'Crunches with Stability Ball',
    'exercise.crunchesWithStabilityBall.howTo': 'Lie on your back with legs resting on a stability ball. Place hands behind your head. Engage your core and curl your upper body up, lifting shoulder blades off the floor. Lower with control.',
    'exercise.declineCrunch.name': 'Decline Crunch',
    'exercise.declineCrunch.howTo': 'Secure your legs on a decline bench with your head lower than your feet. Cross your arms over your chest or place hands behind head. Curl your upper body up towards your thighs, then lower with control.',
    'exercise.dumbbellDeclineFlys.name': 'Dumbbell Decline Flys',
    'exercise.dumbbellDeclineFlys.howTo': 'Lie on a decline bench with dumbbells held above your chest. Lower the weights out to the sides in an arc until you feel a stretch in your chest. Squeeze your chest to bring the weights back together.',
    'exercise.kneelingTricepsExtension.name': 'Kneeling Concentration Triceps Extension',
    'exercise.kneelingTricepsExtension.howTo': 'Kneel beside a cable machine, grasp the handle with one hand. Extend your arm downward, focusing on contracting the triceps. Return to the starting position with control.',
    'exercise.dumbbellFrontRaisesAlt.name': 'Dumbbell Front Raises (Alternating)',
    'exercise.dumbbellFrontRaisesAlt.howTo': 'Stand with feet shoulder-width apart holding dumbbells at your sides. Raise one arm straight in front to shoulder height, then lower. Alternate arms for each rep.',
    'exercise.dumbbellLateralRaises.name': 'Dumbbell Lateral Raises',
    'exercise.dumbbellLateralRaises.howTo': 'Stand with feet shoulder-width apart, holding dumbbells at your sides. Raise both arms out to the sides until they reach shoulder height, keeping a slight bend in your elbows. Lower slowly back down.',
    'exercise.exerciseBallPullIn.name': 'Exercise Ball Pull-In',
    'exercise.exerciseBallPullIn.howTo': 'Start in a push-up position with your shins on an exercise ball. Pull your knees toward your chest by rolling the ball forward. Extend your legs back to the starting position.',
    'exercise.girondaSternumChins.name': 'Gironda Sternum Chins',
    'exercise.girondaSternumChins.howTo': 'Hang from a pull-up bar with a wide grip. Pull yourself up while leaning back, bringing your sternum toward the bar. Lower yourself with control.',
    'exercise.hammerCurlsRope.name': 'Hammer Curls with Rope',
    'exercise.hammerCurlsRope.howTo': 'Stand facing a low cable pulley with a rope attachment. Grip the rope with a neutral grip and curl upward, keeping elbows close to your sides. Lower with control.',
    'exercise.highCableCurls.name': 'High Cable Curls',
    'exercise.highCableCurls.howTo': 'Lie on a bench positioned under high cable pulleys. Grasp the handles and curl them toward your head, contracting your biceps. Extend your arms back up with control.',
    'exercise.hyperextensions.name': 'Hyperextensions',
    'exercise.hyperextensions.howTo': 'Position yourself face down on a hyperextension bench with your hips supported. Cross your arms over your chest or behind your head. Lower your torso, then raise back up by contracting your lower back and glutes.',
    'exercise.inclineTricepsExtensions.name': 'Incline Triceps Extensions',
    'exercise.inclineTricepsExtensions.howTo': 'Lie on an incline bench holding dumbbells above your chest. Bend your elbows to lower the weights toward your head, then extend your arms back to the starting position.',
    'exercise.legPress.name': 'Leg Press',
    'exercise.legPress.howTo': 'Sit on the leg press machine with your back flat against the pad. Place feet shoulder-width apart on the platform. Push the platform away by extending your legs, then lower it back by bending your knees to 90 degrees. Keep your lower back pressed against the seat.',
    'exercise.legRaises.name': 'Leg Raises',
    'exercise.legRaises.howTo': 'Lie flat on your back with legs extended. Place your hands under your lower back for support. Keeping legs straight, lift them up until they form a 90-degree angle with your torso. Lower them back down slowly without touching the floor.',
    'exercise.lowTricepsExtension.name': 'Low Triceps Extension',
    'exercise.lowTricepsExtension.howTo': 'Lie on your back with a dumbbell in each hand. Start with arms extended toward the ceiling. Bend at the elbows to lower the weights toward your shoulders, keeping upper arms stationary. Extend back up to the starting position.',
    'exercise.lungesBarbell.name': 'Lunges (Barbell)',
    'exercise.lungesBarbell.howTo': 'Stand with a barbell across your upper back. Step forward with one leg and lower your hips until both knees are bent at 90 degrees. Push through your front heel to return to standing. Alternate legs or complete all reps on one side first.',
    'exercise.lungesDumbbell.name': 'Lunges (Dumbbell)',
    'exercise.lungesDumbbell.howTo': 'Stand holding dumbbells at your sides. Step forward with one leg and lower your body until both knees form 90-degree angles. Keep your torso upright and core engaged. Push back to starting position and alternate legs.',
    'exercise.lyingCloseGripTricepsPress.name': 'Lying Close-Grip Triceps Press',
    'exercise.lyingCloseGripTricepsPress.howTo': 'Lie on a flat bench holding a barbell with a narrow grip. Lower the bar towards your chin by bending your elbows, keeping upper arms stationary. Press the bar back up by extending your arms. Focus on squeezing your triceps at the top.',
    'exercise.lyingOneArmRearLateralRaise.name': 'Lying One-Arm Rear Lateral Raise',
    'exercise.lyingOneArmRearLateralRaise.howTo': 'Lie face down on an incline bench, holding a dumbbell in one hand. Let your arm hang straight down. Raise the dumbbell out to the side until your arm is parallel to the floor. Lower slowly and repeat. Switch arms after completing reps.',
    'exercise.lyingRearLateralRaise.name': 'Lying Rear Lateral Raise',
    'exercise.lyingRearLateralRaise.howTo': 'Lie face down on an incline bench holding dumbbells in both hands. Let your arms hang straight down with palms facing each other. Raise both arms out to the sides until parallel to the floor. Lower slowly with control.',
    'exercise.oneArmShoulderPress.name': 'One-Arm Shoulder Press',
    'exercise.oneArmShoulderPress.howTo': 'Stand holding a dumbbell at shoulder height with one hand. Press the weight overhead until your arm is fully extended. Lower it back to shoulder height with control. Complete all reps on one side before switching arms.',
    'exercise.oneArmTricepsExtension.name': 'One-Arm Triceps Extension',
    'exercise.oneArmTricepsExtension.howTo': 'Sit on a bench holding a dumbbell in one hand overhead. Keep your upper arm stationary and lower the weight behind your head by bending your elbow. Extend your arm back up to the starting position. Switch arms after completing reps.',
    'exercise.oneArmUprightRow.name': 'One-Arm Upright Row',
    'exercise.oneArmUprightRow.howTo': 'Stand holding a dumbbell in one hand at your thigh. Pull the weight up along your body to chest level, leading with your elbow. Keep your elbow higher than your hand throughout. Lower with control and repeat.',
    'exercise.lyingTricepsExtensionAcrossFace.name': 'Lying Triceps Extension Across Face',
    'exercise.lyingTricepsExtensionAcrossFace.howTo': 'Lie on a flat bench holding dumbbells above your chest. Lower the weights toward your face by bending your elbows, keeping upper arms stationary. Extend back up to the starting position, squeezing your triceps at the top.',
    'exercise.medicineBallBicepsCurl.name': 'Medicine Ball Biceps Curl on Stability Ball',
    'exercise.medicineBallBicepsCurl.howTo': 'Sit on a stability ball holding a medicine ball with both hands. Keep your elbows at your sides and curl the ball up toward your chest. Lower slowly with control. The stability ball adds core engagement to the exercise.',
    'exercise.narrowGripBenchPress.name': 'Narrow Grip Bench Press',
    'exercise.narrowGripBenchPress.howTo': 'Lie on a flat bench and grip the barbell with hands closer than shoulder-width apart. Lower the bar to your lower chest, keeping elbows close to your body. Press back up to the starting position. This targets the triceps more than a regular bench press.',
    'exercise.oneArmBenchPress.name': 'One-Arm Bench Press',
    'exercise.oneArmBenchPress.howTo': 'Lie on a flat bench holding a dumbbell in one hand above your chest. Lower the weight to the side of your chest, then press it back up. Keep your core tight to maintain balance. Complete all reps before switching arms.',
    'exercise.oneArmBicepConcentrationStabilityBall.name': 'One-Arm Bicep Concentration on Stability Ball',
    'exercise.oneArmBicepConcentrationStabilityBall.howTo': 'Sit on a stability ball with legs apart, holding a dumbbell in one hand. Rest your elbow on the inside of your thigh. Curl the weight up toward your shoulder, squeezing your bicep at the top. Lower slowly and repeat.',
    'exercise.oneArmPreacherCurl.name': 'One-Arm Preacher Curl',
    'exercise.oneArmPreacherCurl.howTo': 'Position yourself at a preacher bench or lean over with your arm supported. Hold a dumbbell with your arm extended. Curl the weight up toward your shoulder, focusing on the bicep contraction. Lower with control and repeat.',
    'exercise.spiderCurl.name': 'Spider Curl',
    'exercise.spiderCurl.howTo': 'Lie face down on an incline bench with your arms hanging straight down holding a barbell. Curl the weight up toward your shoulders while keeping your upper arms stationary. Squeeze your biceps at the top and lower with control.',
    'exercise.preacherCurlBarbell.name': 'Preacher Curl (Barbell)',
    'exercise.preacherCurlBarbell.howTo': 'Sit at a preacher bench with your upper arms resting on the pad. Grip a barbell with an underhand grip. Curl the bar up toward your shoulders, then lower it back down with control. Keep your upper arms pressed against the pad throughout.',
    'exercise.pulloverStabilityBall.name': 'Pullover on Stability Ball',
    'exercise.pulloverStabilityBall.howTo': 'Lie with your upper back on a stability ball, feet flat on the floor. Hold a dumbbell with both hands above your chest. Lower the weight behind your head in an arc, then pull it back over your chest. Keep your core engaged for stability.',
    'exercise.pushUpFeetOnBall.name': 'Push-Up with Feet on Exercise Ball',
    'exercise.pushUpFeetOnBall.howTo': 'Place your feet on a stability ball and your hands on the floor in a push-up position. Lower your chest toward the floor by bending your elbows, then push back up. The unstable surface engages your core throughout the movement.',
    'exercise.rearDeltoidRow.name': 'Rear Deltoid Row',
    'exercise.rearDeltoidRow.howTo': 'Place one hand and knee on a bench for support. Hold a dumbbell in your other hand with arm extended. Row the weight up toward your hip, focusing on squeezing your rear deltoid. Lower with control and repeat.',
    'exercise.reversePlateCurls.name': 'Reverse Plate Curls',
    'exercise.reversePlateCurls.howTo': 'Stand holding a weight plate with both hands in front of your thighs, thumbs on top. Curl the plate up toward your chest while keeping your elbows at your sides. Lower with control. This targets the forearms and biceps.',
    'exercise.seatedTricepsPress.name': 'Seated Triceps Press',
    'exercise.seatedTricepsPress.howTo': 'Sit on a bench holding a dumbbell with both hands behind your head. Extend your arms to press the weight overhead, then lower it back behind your head. Keep your elbows close to your head throughout the movement.',
    'exercise.tricepDips.name': 'Tricep Dips (Bench)',
    'exercise.tricepDips.howTo': 'Sit on the edge of a bench with hands gripping the edge beside your hips. Slide your hips off the bench with legs extended. Lower your body by bending your elbows to about 90 degrees, then push back up. Keep your back close to the bench.',
    'exercise.parallelBarDips.name': 'Parallel Bar Dips',
    'exercise.parallelBarDips.howTo': 'Grip parallel bars and lift yourself up with arms fully extended. Lower your body by bending your elbows until your upper arms are parallel to the floor. Push back up to the starting position. Keep your core tight throughout.',
    'exercise.barbellSquat.name': 'Barbell Squat',
    'exercise.barbellSquat.howTo': 'Stand with a barbell across your upper back, feet shoulder-width apart. Lower your body by bending your knees and hips as if sitting back into a chair. Go down until your thighs are parallel to the floor, then drive back up.',
    'exercise.smithMachineSquat.name': 'Smith Machine Squat',
    'exercise.smithMachineSquat.howTo': 'Position yourself under the Smith machine bar with it across your upper back. Unrack the bar and lower your body by bending your knees. Go down until thighs are parallel to the floor, then push back up. The machine guides your movement.',
    'exercise.dumbbellSquat.name': 'Dumbbell Squat',
    'exercise.dumbbellSquat.howTo': 'Stand holding dumbbells at your sides, feet shoulder-width apart. Lower your body by bending your knees and pushing your hips back. Keep your chest up and go down until thighs are parallel to the floor, then stand back up.',
    'exercise.bandSquat.name': 'Resistance Band Squat',
    'exercise.bandSquat.howTo': 'Stand on a resistance band with feet shoulder-width apart, holding the handles at shoulder height. Lower into a squat position, keeping tension on the band. Push through your heels to stand back up, maintaining control throughout.',
    'exercise.stabilityBallCrunch.name': 'Stability Ball Abdominal Crunch',
    'exercise.stabilityBallCrunch.howTo': 'Lie with your lower back on a stability ball, feet flat on the floor. Place your hands behind your head or across your chest. Crunch up by contracting your abs, lifting your shoulders toward the ceiling. Lower back down with control.',
    'exercise.standingBandCurl.name': 'Standing Resistance Band Curl',
    'exercise.standingBandCurl.howTo': 'Stand on a resistance band with feet shoulder-width apart, holding the handles with palms facing up. Keep your elbows at your sides and curl the handles up toward your shoulders. Lower with control and repeat.',
    'exercise.tBarRow.name': 'T-Bar Row',
    'exercise.tBarRow.howTo': 'Stand on the T-bar row platform with feet shoulder-width apart. Bend forward at the hips and grip the handles. Pull the weight up toward your chest, squeezing your shoulder blades together. Lower with control and repeat.',
    'exercise.tricepsKickback.name': 'Triceps Kickback',
    'exercise.tricepsKickback.howTo': 'Place one hand and knee on a bench for support. Hold a dumbbell in your other hand with your upper arm parallel to the floor and elbow bent at 90 degrees. Extend your arm back until it is straight, squeezing your triceps. Lower with control and repeat.',
    'exercise.lyingCloseGripBicepsCurls.name': 'Lying Close-Grip Biceps Curls',
    'exercise.lyingCloseGripBicepsCurls.howTo': 'Lie on a flat bench holding a barbell with a close grip. Start with arms extended above your chest. Curl the bar down toward your forehead by bending your elbows, keeping upper arms stationary. Extend back up and repeat.',
    'exercise.frontRaiseAndPullover.name': 'Front Raise and Pullover',
    'exercise.frontRaiseAndPullover.howTo': 'Lie on a flat bench holding a barbell with extended arms above your chest. Lower the weight behind your head in an arc, then raise it back up and continue forward for a front raise motion. Return to start position.',
    'exercise.hackSquats.name': 'Hack Squats',
    'exercise.hackSquats.howTo': 'Position yourself on the hack squat machine with your back against the pad and shoulders under the supports. Place feet shoulder-width apart on the platform. Lower your body by bending your knees, then push back up.',
    'exercise.inclineBicepsCurl.name': 'Incline Biceps Curl',
    'exercise.inclineBicepsCurl.howTo': 'Sit on an incline bench holding dumbbells at your sides with arms fully extended. Curl the weights up toward your shoulders while keeping your upper arms stationary. Lower with control and repeat.',
    'exercise.inclinePushdown.name': 'Incline Pushdown',
    'exercise.inclinePushdown.howTo': 'Sit on an incline bench facing a cable machine with the pulley set high. Grasp the rope or bar attachment. Push the weight down by extending your elbows, squeezing your triceps at the bottom. Return with control.',
    'exercise.inclineTricepsExtensionCable.name': 'Incline Triceps Extension (Cable)',
    'exercise.inclineTricepsExtensionCable.howTo': 'Sit on an incline bench facing away from a low cable pulley. Hold the rope behind your head with elbows bent. Extend your arms overhead by straightening your elbows. Lower back with control.',
    'exercise.inclineTricepsExtensionBarbell.name': 'Incline Triceps Extension (Barbell)',
    'exercise.inclineTricepsExtensionBarbell.howTo': 'Lie on an incline bench holding a barbell with extended arms above your chest. Lower the bar toward your forehead by bending your elbows. Extend back up, squeezing your triceps at the top.',
    'exercise.jmPress.name': 'JM Press',
    'exercise.jmPress.howTo': 'Lie on a flat bench holding a barbell with a close grip above your chest. Lower the bar by bending elbows and bringing the bar toward your chin/upper chest, combining a press and extension. Press back up.',
    'exercise.oneArmBicepCurlOlympicBar.name': 'One-Arm Bicep Curl with Olympic Bar',
    'exercise.oneArmBicepCurlOlympicBar.howTo': 'Stand holding an Olympic barbell at one end with one hand. Keep your elbow at your side and curl the bar up toward your shoulder. Lower with control and repeat. This builds grip strength along with biceps.',
    'exercise.lyingCloseGripTricepsExtensionBehindHead.name': 'Lying Close-Grip Triceps Extension Behind Head',
    'exercise.lyingCloseGripTricepsExtensionBehindHead.howTo': 'Lie on a flat bench holding a barbell with a close grip. Lower the bar behind your head by bending your elbows. Extend your arms back up, squeezing your triceps at the top.',
    'exercise.lyingHighBenchBicepsCurl.name': 'Lying High Bench Biceps Curl',
    'exercise.lyingHighBenchBicepsCurl.howTo': 'Lie face down on a high bench with arms hanging down. Hold a barbell and curl it up toward your shoulders while keeping your upper arms stationary. Lower with control.',
    'exercise.lyingInclineCurl.name': 'Lying Incline Curl',
    'exercise.lyingInclineCurl.howTo': 'Lie face down on an incline bench with arms hanging down. Hold a barbell and curl it up toward your shoulders. The incline position provides a unique stretch on the biceps.',
    'exercise.lyingSupineBicepsCurl.name': 'Lying Supine Biceps Curl',
    'exercise.lyingSupineBicepsCurl.howTo': 'Lie on your back on a flat bench with arms hanging down holding dumbbells. Curl the weights up toward your shoulders while keeping your upper arms stationary. Lower with control.',
    'exercise.lyingSupineTwoArmTricepsExtension.name': 'Lying Supine Two-Arm Triceps Extension',
    'exercise.lyingSupineTwoArmTricepsExtension.howTo': 'Lie on a flat bench holding dumbbells with arms extended above your chest. Lower the weights by bending your elbows until they are beside your head. Extend back up, squeezing triceps.',
    'exercise.lyingTricepsExtensionCable.name': 'Lying Triceps Extension (Cable)',
    'exercise.lyingTricepsExtensionCable.howTo': 'Lie on a bench with head near a low cable pulley. Grasp the rope or bar with arms extended overhead. Lower the attachment behind your head by bending elbows. Extend back up.',
    'exercise.lyingTricepsExtensionDumbbell.name': 'Lying Triceps Extension (Dumbbell)',
    'exercise.lyingTricepsExtensionDumbbell.howTo': 'Lie on a flat bench holding a dumbbell with both hands above your chest. Lower the weight behind your head by bending your elbows. Extend back up, squeezing your triceps.',
    'exercise.lyingTricepsPress.name': 'Lying Triceps Press',
    'exercise.lyingTricepsPress.howTo': 'Lie on a flat bench holding a barbell above your chest with arms extended. Lower the bar toward your forehead by bending your elbows. Press back up to the starting position.',
    'exercise.weightedSissySquat.name': 'Weighted Sissy Squat',
    'exercise.weightedSissySquat.howTo': 'Stand next to a pole or support, holding it for balance with one hand. Hold a weight plate against your chest with the other hand. Rise onto your toes, then lean back while bending your knees forward. Lower down until your thighs are parallel to the floor, keeping your torso and thighs in a straight line. Push back up through your toes.',
    'exercise.thighAdductor.name': 'Thigh Adductor',
    'exercise.thighAdductor.howTo': 'Sit on the adductor machine with your back against the pad and legs spread apart on the leg pads. Squeeze your inner thighs together to bring the pads inward against the resistance. Hold briefly at the center, then slowly return to the starting position with control.',
    'exercise.standingTricepsExtension.name': 'Standing Triceps Extension',
    'exercise.standingTricepsExtension.howTo': 'Stand with feet shoulder-width apart, holding a dumbbell with both hands above your head, arms fully extended. Keep your upper arms close to your ears and slowly lower the weight behind your head by bending at the elbows. Extend your arms back up to the starting position, squeezing your triceps at the top.',
    'exercise.smithMachineRearDeltoidRow.name': 'Smith Machine Rear Deltoid Row',
    'exercise.smithMachineRearDeltoidRow.howTo': 'Stand facing a Smith machine with the bar set at thigh height. Bend forward at the hips with a slight bend in your knees. Grip the bar wider than shoulder-width with an overhand grip. Pull the bar up toward your chest by squeezing your shoulder blades together and driving your elbows out. Lower the bar with control.',
    'exercise.seatedOverheadTricepsExtension.name': 'Seated Overhead Triceps Extension',
    'exercise.seatedOverheadTricepsExtension.howTo': 'Sit on a bench with back support, holding a barbell overhead with arms fully extended. Keep your upper arms stationary and close to your head. Lower the bar behind your head by bending at the elbows. Extend your arms back up, squeezing your triceps at the top.',
    'exercise.wideGripLatPullDown.name': 'Wide Grip Lat Pull Down',
    'exercise.wideGripLatPullDown.howTo': 'Sit at a lat pulldown machine with your thighs secured under the pads. Grab the bar with a wide overhand grip, hands wider than shoulder-width. Pull the bar down to your upper chest while squeezing your shoulder blades together. Slowly extend your arms back up with control, feeling the stretch in your lats.',
    'exercise.walkingLunges.name': 'Walking Lunges',
    'exercise.walkingLunges.howTo': 'Stand tall holding dumbbells at your sides. Step forward with one leg and lower your body until both knees are bent at 90 degrees. Push through your front heel and bring your back leg forward to take the next step. Continue walking forward, alternating legs with each step. Keep your torso upright and core engaged throughout.',
    'exercise.aerobics.name': 'Step Aerobics',
    'exercise.aerobics.howTo': 'Use a step platform and follow rhythmic stepping patterns. Step up with one foot, then the other, then step down. Vary movements with kicks, knee lifts, and arm movements. Keep your core engaged and maintain a steady pace for cardiovascular benefits.',
    'exercise.mountainBiking.name': 'Mountain Biking',
    'exercise.mountainBiking.howTo': 'Ride a mountain bike on off-road trails and rough terrain. Maintain proper posture with slightly bent elbows and knees. Shift your weight back when going downhill and forward when climbing. Use both brakes evenly and keep your eyes on the trail ahead.',
    'exercise.pilates.name': 'Pilates',
    'exercise.pilates.howTo': 'Perform controlled movements focusing on core strength and flexibility. Maintain proper alignment and breathing throughout. Common exercises include the hundred, roll-up, and plank variations. Move with precision and control rather than speed.',
    'exercise.recumbentBiking.name': 'Recumbent Biking',
    'exercise.recumbentBiking.howTo': 'Sit in a reclined position on a recumbent bike with your back supported. Adjust the seat so your legs have a slight bend at full extension. Pedal at a steady pace while maintaining good posture. Great for low-impact cardio with reduced stress on joints.',
    'exercise.roadCycling.name': 'Road Cycling',
    'exercise.roadCycling.howTo': 'Ride a road bike on paved surfaces at a steady pace. Maintain an aerodynamic position with hands on the handlebars. Pedal in smooth circular motions and shift gears based on terrain. Keep your cadence consistent for efficient energy use.',
    'exercise.rowing.name': 'Rowing Machine',
    'exercise.rowing.howTo': 'Sit on the rowing machine with feet strapped in. Drive with your legs first, then lean back slightly while pulling the handle to your lower chest. Reverse the motion by extending arms, hinging forward, then bending knees. Keep your core engaged throughout.',
    'exercise.running.name': 'Running',
    'exercise.running.howTo': 'Start with a warm-up walk, then gradually increase your pace to a comfortable run. Land midfoot with each stride and keep your arms relaxed at a 90-degree angle. Breathe rhythmically and maintain good posture with your head up and shoulders relaxed.',
    'exercise.spinning.name': 'Spinning / Indoor Cycling',
    'exercise.spinning.howTo': 'Ride a stationary spin bike following a workout routine. Adjust resistance to simulate hills and sprints. Stand up for climbing sections and sit for sprints. Keep your core tight and maintain a steady cadence. Follow the instructor or program for varied intensity.',
    'exercise.stepMachine.name': 'Stair Climber',
    'exercise.stepMachine.howTo': 'Stand on the stair climber with hands lightly on the rails for balance. Step up in a controlled manner, pushing through your heels. Avoid leaning heavily on the rails. Maintain an upright posture and keep a steady rhythm for effective cardio.',
    'exercise.swimming.name': 'Swimming',
    'exercise.swimming.howTo': 'Enter the water and perform your chosen stroke with proper technique. For freestyle, rotate your body and breathe to the side. Keep your core engaged and legs kicking continuously. Maintain a streamlined position to reduce drag and improve efficiency.',
    'exercise.treadmillRunning.name': 'Treadmill Running',
    'exercise.treadmillRunning.howTo': 'Start the treadmill at a slow walking pace and gradually increase speed. Run with a natural stride, landing midfoot. Use the incline feature to simulate outdoor terrain. Keep your posture upright and avoid holding onto the rails while running.',
    'exercise.walking.name': 'Brisk Walking',
    'exercise.walking.howTo': 'Walk at a brisk pace that elevates your heart rate. Swing your arms naturally and take purposeful strides. Keep your head up and shoulders back. Walk for at least 30 minutes for cardiovascular benefits. Can be done outdoors or on a treadmill.',
    'exercise.yoga.name': 'Yoga',
    'exercise.yoga.howTo': 'Practice various yoga poses focusing on flexibility, balance, and mindfulness. Move through poses with controlled breathing. Hold each position for several breaths. Start with basic poses and progress to more advanced ones as flexibility improves.',
    
    // Calculator page
    'calculator.hero.title': 'BMI Calculator',
    'calculator.hero.subtitle': 'Calculate your Body Mass Index and understand your health metrics',
    'calculator.title': 'Calculate Your BMI',
    'calculator.description': 'Enter your weight and height to calculate your Body Mass Index',
    'calculator.weight': 'Weight (kg)',
    'calculator.weightPlaceholder': 'Enter your weight in kg',
    'calculator.height': 'Height (cm)',
    'calculator.heightPlaceholder': 'Enter your height in cm',
    'calculator.calculate': 'Calculate BMI',
    'calculator.yourBmi': 'Your BMI',
    'calculator.categories': 'BMI Categories',
    'calculator.underweight': 'Underweight',
    'calculator.normal': 'Normal weight',
    'calculator.overweight': 'Overweight',
    'calculator.obese': 'Obese',
    
    // Support Groups
    'support.title': 'Anonymous Support Groups',
    'support.subtitle': 'Connect with others, share experiences, and support each other on your health and wellness journey',
    'support.createTopic': 'Create New Topic',
    'support.newTopic': 'New Support Topic',
    'support.topicTitle': 'Topic Title',
    'support.description': 'Description',
    'support.category': 'Category',
    'support.create': 'Create Topic',
    'support.topics': 'Topics',
    'support.username': 'Your name (optional, leave blank for Anonymous)',
    'support.reply': 'Share your thoughts...',
    'support.post': 'Post Reply',
    'support.selectTopic': 'Select a topic to view discussions',
    'support.success': 'Success',
    'support.topicCreated': 'Topic created successfully',
    'support.deleted': 'Deleted successfully',
    'support.updated': 'Updated successfully',
    'support.save': 'Save',
    'support.cancel': 'Cancel',
    'support.categories.mental': 'Mental Health',
    'support.categories.fitness': 'Exercise & Fitness',
    'support.categories.chronic': 'Chronic Conditions',
    'support.categories.wellness': 'General Wellness',
    'support.categories.sleep': 'Sleep & Rest',

    // Workout Generator
    'generator.title': 'Create Your Workout Plan',
    'generator.duration': 'Workout Duration',
    'generator.durationDesc': 'How long do you want to work out?',
    'generator.minutes': 'minutes',
    'generator.intensity': 'Intensity Level',
    'generator.intensityDesc': 'Choose your preferred intensity',
    'generator.low': 'Low',
    'generator.medium': 'Medium',
    'generator.high': 'High',
    'generator.equipment': 'Available Equipment',
    'generator.equipmentDesc': 'Select the equipment you have access to',
    'generator.generate': 'Generate Workout Plan',
    'generator.generating': 'Creating your plan...',
    'generator.error': 'Error generating plan',
    'generator.tryAgain': 'Please try again',

    // Workout Plan View
    'plan.title': 'Your Workout Plan',
    'plan.noplan': 'No workout plan yet',
    'plan.create': 'Create one using the generator',
    'plan.exercise': 'Exercise',
    'plan.sets': 'Sets',
    'plan.reps': 'Reps',
    'plan.rest': 'Rest',
    'plan.seconds': 'seconds',
    'plan.clear': 'Clear Plan',
  },
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.events': 'Eventos',
    'nav.workouts': 'Exercícios',
    'nav.calculator': 'Calculadora',
    'nav.support': 'Grupos de Apoio Anônimos',
    
    // Home page
    'home.hero.title': 'Sua Jornada para uma Melhor Saúde Começa Aqui',
    'home.hero.subtitle': 'Junte-se à nossa comunidade dedicada a promover boa saúde e bem-estar',
    'home.hero.viewWorkouts': 'Ver Exercícios',
    'home.hero.checkBMI': 'Verificar IMC',
    'home.features.title': 'Por que Escolher PROACTIVE?',
    'home.features.events.title': 'Encontrar Eventos',
    'home.features.events.desc': 'Participe de eventos de saúde e fitness',
    'home.features.bmi.title': 'Calculadora de IMC',
    'home.features.bmi.desc': 'Acompanhe suas métricas de saúde e entenda melhor seu corpo',
    'home.features.workouts.title': 'Exercícios',
    'home.features.workouts.desc': 'Transforme sua forma física com nossos exercícios projetados',
    'home.features.advocacy.title': 'Saúde & Bem-estar',
    'home.features.advocacy.desc': 'Capacitando você com conhecimento para um estilo de vida mais saudável',
    'home.blog.title': 'Saúde & Bem-estar',
    'home.blog.subtitle': 'Descubra dicas e fatos para melhorar sua vida diária',
    'home.blog.readMore': 'Leia mais',
    'home.newsletter.title': 'Mantenha-se Atualizado',
    'home.newsletter.desc': 'Inscreva-se para receber dicas de saúde e atualizações',
    'home.newsletter.placeholder': 'Digite seu e-mail',
    'home.newsletter.button': 'Inscrever-se',
    'home.newsletter.success': 'Inscrito com sucesso na newsletter!',
    'home.cta.title': 'Pronto para Iniciar Sua Jornada de Saúde?',
    'home.cta.subtitle': 'Junte-se a milhares de pessoas que já estão melhorando sua saúde com o PROACTIVE',
    'home.cta.bmi': 'Calcule Seu IMC',
    'home.cta.workouts': 'Comece a Treinar',

    // Did You Know Posts
    'didyouknow.title': 'Você Sabia?',
    'didyouknow.subtitle': 'Descubra fatos interessantes de saúde e dicas para melhorar sua vida diária',
    'didyouknow.hydration.title': 'Mantenha-se Hidratado',
    'didyouknow.hydration.content': 'A falta de hidratação pode causar cansaço e redução de energia. Manter-se adequadamente hidratado pode aumentar a energia e melhorar o desempenho mental.',
    'didyouknow.sleep.title': 'Sono de Qualidade Importa',
    'didyouknow.sleep.content': 'Dormir de 7 a 9 horas de sono de qualidade por noite pode melhorar a memória e fortalecer o sistema imunológico.',
    'didyouknow.share': 'Compartilhar',
    'didyouknow.imageDownloaded': 'Imagem baixada!',
    'didyouknow.shareDescription': 'Compartilhe em sua rede social favorita.',
    
    // Events page
    'events.hero.title': 'Eventos de Saúde & Fitness',
    'events.hero.subtitle': 'Junte-se aos nossos eventos comunitários e leve sua jornada de bem-estar ao próximo nível',
    'events.title': 'Maratona da Cidade de Bicicleta',
    'events.description': 'Junte-se a nós na Maratona da Cidade de Bicicleta! A corrida começa no Maputo Shopping Centre até Tchumene Circular e volta. Gratuito para participantes com bicicleta e capacete próprios. 200 Meticais para quem precisar de aluguel de bicicleta e capacete.',
    'events.date': '12 de Dezembro de 2026',
    'events.location': 'R. Ngungunhane, Maputo',
    'events.register': 'Registrar Agora',
    'events.viewGallery': 'Ver Galeria',
    'events.addImage': 'Adicionar Imagem',
    'events.enterPassword': 'Digite a senha de administrador',
    'events.imageUrl': 'URL da Imagem',
    'events.uploadImage': 'Carregar do Dispositivo',
    'events.orUpload': 'Ou carregue do seu dispositivo',
    'events.add': 'Adicionar',
    'events.wrongPassword': 'Senha incorreta',
    'events.imageAdded': 'Imagem adicionada com sucesso',
    'events.noImages': 'Nenhuma imagem na galeria ainda. Adicione algumas fotos!',
    'events.notActive': 'Não Ativo',
    
    // Workouts page
    'workouts.hero.title': 'Exercícios',
    'workouts.hero.subtitle': 'Transforme sua forma física com nossos exercícios projetados',
    'workouts.tabs.library': 'Biblioteca de Exercícios',
    'workouts.tabs.generator': 'Criar Plano de Treino',
    'workouts.tabs.plan': 'Meu Plano',
    'workouts.filters.type': 'Tipo',
    'workouts.filters.equipment': 'Equipamento',
    'workouts.filters.muscle': 'Músculo',
    'workouts.filters.allTypes': 'Todos os Tipos',
    'workouts.filters.allEquipment': 'Todos os Equipamentos',
    'workouts.filters.allMuscles': 'Todos os Músculos',
    'workouts.types.strength': 'Força',
    'workouts.types.cardio': 'Cardio',
    'workouts.types.stretching': 'Alongamento',
    'workouts.equipment.bodyweight': 'Peso Corporal',
    'workouts.equipment.barbell': 'Barra',
    'workouts.equipment.dumbbells': 'Halteres',
    'workouts.equipment.bench': 'Banco',
    'workouts.equipment.stabilityball': 'Bola de Estabilidade',
    'workouts.equipment.cable': 'Máquina de Cabo',
    'workouts.equipment.machine': 'Máquina',
    'workouts.muscles.chest': 'Peito',
    'workouts.muscles.triceps': 'Tríceps',
    'workouts.muscles.shoulders': 'Ombros',
    'workouts.muscles.core': 'Core',
    'workouts.muscles.abs': 'Abdominais',
    'workouts.muscles.back': 'Costas',
    'workouts.howTo': 'Como fazer:',
    'workouts.noResults': 'Nenhum exercício encontrado com seus filtros.',
    'workouts.clickFullscreen': 'Clique para visualizar em tela cheia',

    // Exercise names and instructions
    'exercise.barbellFrontRaises.name': 'Elevação Frontal com Barra',
    'exercise.barbellFrontRaises.howTo': 'Fique em pé com os pés na largura dos ombros, segurando uma barra na frente das coxas com pegada pronada. Mantenha os braços retos e levante a barra até a altura dos ombros, pause brevemente e abaixe lentamente. Concentre-se em movimentos controlados e evite balançar.',
    'exercise.arnoldPress.name': 'Arnold Press',
    'exercise.arnoldPress.howTo': 'Comece sentado com halteres na altura dos ombros, palmas voltadas para você. Ao pressionar os pesos para cima, gire as palmas para frente no topo. Inverta o movimento ao abaixar os pesos. Isso trabalha seus ombros em uma amplitude maior de movimento.',
    'exercise.barbellUprightRows.name': 'Remada Alta com Barra',
    'exercise.barbellUprightRows.howTo': 'Segure uma barra com pegada estreita na frente das coxas. Puxe a barra para cima ao longo do corpo até a altura do peito, mantendo os cotovelos apontando para fora. Abaixe a barra lentamente e repita. Mantenha o core ativado durante todo o movimento.',
    'exercise.backExtension.name': 'Extensão de Costas na Bola de Estabilidade',
    'exercise.backExtension.howTo': 'Deite-se de bruços em uma bola de estabilidade com os quadris na bola e os pés ancorados contra uma parede ou chão. Coloque as mãos atrás da cabeça. Abaixe a parte superior do corpo em direção ao chão, depois levante contraindo os músculos da região lombar. Mantenha os movimentos controlados.',
    'exercise.barbellShrugs.name': 'Encolhimento com Barra',
    'exercise.barbellShrugs.howTo': 'Fique em pé com os pés na largura dos ombros, segurando uma barra com pegada pronada na frente das coxas. Mantenha os braços retos e eleve os ombros em direção às orelhas o máximo possível. Segure brevemente no topo, depois abaixe lentamente. Mantenha o core contraído.',
    'exercise.benchDips.name': 'Mergulho no Banco',
    'exercise.benchDips.howTo': 'Coloque as mãos em um banco atrás de você com os dedos voltados para frente. Estenda as pernas à frente. Abaixe o corpo dobrando os cotovelos até que os braços fiquem paralelos ao chão. Empurre de volta à posição inicial. Mantenha as costas próximas ao banco.',
    'exercise.benchPress.name': 'Supino',
    'exercise.benchPress.howTo': 'Deite-se em um banco plano com os pés apoiados no chão. Segure a barra um pouco mais larga que a largura dos ombros. Abaixe a barra lentamente até o meio do peito, pause brevemente e pressione de volta. Mantenha o core contraído e uma leve curva na lombar.',
    'exercise.bentArmPullover.name': 'Pullover com Braços Dobrados',
    'exercise.bentArmPullover.howTo': 'Deite-se em um banco com apenas a parte superior das costas apoiada. Segure uma barra com os braços dobrados em 90 graus. Abaixe o peso atrás da cabeça em arco, sentindo um alongamento nos dorsais. Puxe o peso de volta usando o peito e dorsais.',
    'exercise.bentKneeHipRaise.name': 'Elevação de Quadril com Joelhos Dobrados',
    'exercise.bentKneeHipRaise.howTo': 'Deite-se de costas com os braços ao lado do corpo e joelhos dobrados em 90 graus. Levante os quadris do chão contraindo os abdominais e trazendo os joelhos em direção ao peito. Abaixe com controle. Foque em usar os abdominais inferiores.',
    'exercise.bicepCurlsBarbell.name': 'Rosca Bíceps com Barra',
    'exercise.bicepCurlsBarbell.howTo': 'Fique em pé com os pés na largura dos ombros, segurando uma barra com pegada supinada. Mantenha os cotovelos junto ao corpo. Curve a barra até os ombros, contraindo os bíceps no topo. Abaixe lentamente. Evite balançar ou usar impulso.',
    'exercise.hammerCurl.name': 'Rosca Martelo',
    'exercise.hammerCurl.howTo': 'Fique em pé com os pés na largura dos quadris, segurando halteres ao lado do corpo com as palmas voltadas para dentro (pegada neutra). Curve os pesos até os ombros, mantendo a pegada neutra. Abaixe lentamente e repita. Trabalha bíceps e antebraços.',
    'exercise.bicepsCurlDumbbell.name': 'Rosca Bíceps com Halteres',
    'exercise.bicepsCurlDumbbell.howTo': 'Fique em pé segurando halteres ao lado do corpo com as palmas voltadas para frente. Curve ambos os pesos até os ombros mantendo os cotovelos fixos. Contraia no topo, depois abaixe com controle. Pode alternar braços ou curvar simultaneamente.',
    'exercise.dumbbellFlys.name': 'Crucifixo com Halteres',
    'exercise.dumbbellFlys.howTo': 'Deite em um banco plano com um halter em cada mão. Comece com os braços estendidos acima do peito, palmas voltadas uma para a outra. Abaixe os pesos para os lados em arco até sentir um alongamento no peito. Contraia os músculos do peito para juntar os pesos.',
    'exercise.dumbbellFrontRaises.name': 'Elevação Frontal com Halteres',
    'exercise.dumbbellFrontRaises.howTo': 'Fique em pé com os pés na largura dos ombros, segurando um halter em cada mão nas coxas. Mantenha os braços retos e levante os pesos à frente até a altura dos ombros. Abaixe lentamente e repita. Foque em movimentos controlados.',
    'exercise.bicepsCurlReverse.name': 'Rosca Bíceps Reversa',
    'exercise.bicepsCurlReverse.howTo': 'Fique em pé com halteres ao lado, palmas voltadas para trás (pegada pronada). Curve os pesos até os ombros mantendo a pegada pronada. Abaixe com controle. Esta variação trabalha os antebraços e braquial.',
    'exercise.bridge.name': 'Ponte',
    'exercise.bridge.howTo': 'Deite de costas com os joelhos dobrados e pés apoiados no chão. Empurre pelos calcanhares para levantar os quadris do chão até o corpo formar uma linha reta dos ombros aos joelhos. Contraia os glúteos no topo, depois abaixe lentamente.',
    'exercise.concentrationCurls.name': 'Rosca Concentrada',
    'exercise.concentrationCurls.howTo': 'Sente em um banco com as pernas abertas. Apoie o cotovelo na parte interna da coxa enquanto segura um halter. Curve o peso até o ombro, focando em contrair o bíceps. Abaixe lentamente e repita.',
    'exercise.crossBodyCrunch.name': 'Abdominal Cruzado',
    'exercise.crossBodyCrunch.howTo': 'Deite de costas com as mãos atrás da cabeça e joelhos dobrados. Levante as escápulas do chão e gire para trazer o cotovelo direito em direção ao joelho esquerdo. Retorne e repita do outro lado. Foque no movimento de torção.',
    'exercise.crunches.name': 'Abdominais',
    'exercise.crunches.howTo': 'Deite de costas com os joelhos dobrados e mãos atrás da cabeça. Contraia o core e levante as escápulas do chão. Segure brevemente no topo, depois abaixe com controle. Evite puxar o pescoço.',
    'exercise.crunchesWithStabilityBall.name': 'Abdominais com Bola de Estabilidade',
    'exercise.crunchesWithStabilityBall.howTo': 'Deite de costas com as pernas apoiadas em uma bola de estabilidade. Coloque as mãos atrás da cabeça. Contraia o core e curve o tronco para cima, levantando as escápulas do chão. Abaixe com controle.',
    'exercise.declineCrunch.name': 'Abdominal Declinado',
    'exercise.declineCrunch.howTo': 'Prenda as pernas em um banco declinado com a cabeça mais baixa que os pés. Cruze os braços sobre o peito ou coloque as mãos atrás da cabeça. Curve o tronco em direção às coxas, depois abaixe com controle.',
    'exercise.dumbbellDeclineFlys.name': 'Crucifixo Declinado com Halteres',
    'exercise.dumbbellDeclineFlys.howTo': 'Deite em um banco declinado com halteres acima do peito. Abaixe os pesos para os lados em arco até sentir um alongamento no peito. Contraia o peito para juntar os pesos novamente.',
    'exercise.kneelingTricepsExtension.name': 'Extensão de Tríceps Ajoelhado com Concentração',
    'exercise.kneelingTricepsExtension.howTo': 'Ajoelhe ao lado de uma máquina de cabo, segure a alça com uma mão. Estenda o braço para baixo, focando na contração do tríceps. Retorne à posição inicial com controle.',
    'exercise.dumbbellFrontRaisesAlt.name': 'Elevação Frontal com Halteres (Alternada)',
    'exercise.dumbbellFrontRaisesAlt.howTo': 'Fique de pé com os pés na largura dos ombros segurando halteres ao lado do corpo. Levante um braço reto à frente até a altura do ombro, depois abaixe. Alterne os braços a cada repetição.',
    'exercise.dumbbellLateralRaises.name': 'Elevação Lateral com Halteres',
    'exercise.dumbbellLateralRaises.howTo': 'Fique de pé com os pés na largura dos ombros, segurando halteres ao lado do corpo. Levante ambos os braços para os lados até a altura dos ombros, mantendo uma leve flexão nos cotovelos. Abaixe lentamente.',
    'exercise.exerciseBallPullIn.name': 'Encolhimento com Bola de Exercício',
    'exercise.exerciseBallPullIn.howTo': 'Comece em posição de flexão com as canelas sobre uma bola de exercício. Puxe os joelhos em direção ao peito rolando a bola para frente. Estenda as pernas de volta à posição inicial.',
    'exercise.girondaSternumChins.name': 'Barra Gironda para o Esterno',
    'exercise.girondaSternumChins.howTo': 'Pendure-se em uma barra de pull-up com pegada larga. Puxe-se para cima enquanto se inclina para trás, trazendo o esterno em direção à barra. Desça com controle.',
    'exercise.hammerCurlsRope.name': 'Rosca Martelo com Corda',
    'exercise.hammerCurlsRope.howTo': 'Fique de frente para uma polia baixa com um acessório de corda. Segure a corda com pegada neutra e curve para cima, mantendo os cotovelos próximos ao corpo. Abaixe com controle.',
    'exercise.highCableCurls.name': 'Rosca Alta no Cabo',
    'exercise.highCableCurls.howTo': 'Deite em um banco posicionado sob polias altas. Segure as alças e curve-as em direção à cabeça, contraindo os bíceps. Estenda os braços de volta com controle.',
    'exercise.hyperextensions.name': 'Hiperextensões',
    'exercise.hyperextensions.howTo': 'Posicione-se de bruços em um banco de hiperextensão com os quadris apoiados. Cruze os braços sobre o peito ou atrás da cabeça. Abaixe o tronco, depois levante contraindo a lombar e os glúteos.',
    'exercise.inclineTricepsExtensions.name': 'Extensão de Tríceps Inclinada',
    'exercise.inclineTricepsExtensions.howTo': 'Deite em um banco inclinado segurando halteres acima do peito. Dobre os cotovelos para baixar os pesos em direção à cabeça, depois estenda os braços de volta à posição inicial.',
    'exercise.legPress.name': 'Leg Press',
    'exercise.legPress.howTo': 'Sente-se na máquina de leg press com as costas apoiadas. Coloque os pés na plataforma na largura dos ombros. Empurre a plataforma estendendo as pernas, depois abaixe dobrando os joelhos a 90 graus. Mantenha a lombar pressionada contra o assento.',
    'exercise.legRaises.name': 'Elevação de Pernas',
    'exercise.legRaises.howTo': 'Deite de costas com as pernas estendidas. Coloque as mãos sob a lombar para apoio. Mantendo as pernas retas, levante-as até formar um ângulo de 90 graus com o tronco. Abaixe lentamente sem tocar o chão.',
    'exercise.lowTricepsExtension.name': 'Extensão de Tríceps Deitado',
    'exercise.lowTricepsExtension.howTo': 'Deite de costas com um haltere em cada mão. Comece com os braços estendidos para o teto. Dobre os cotovelos para baixar os pesos em direção aos ombros, mantendo os braços superiores parados. Estenda de volta à posição inicial.',
    'exercise.lungesBarbell.name': 'Avanço com Barra',
    'exercise.lungesBarbell.howTo': 'Fique em pé com uma barra apoiada na parte superior das costas. Dê um passo à frente e abaixe os quadris até que ambos os joelhos estejam dobrados a 90 graus. Empurre pelo calcanhar da frente para retornar. Alterne as pernas.',
    'exercise.lungesDumbbell.name': 'Avanço com Halteres',
    'exercise.lungesDumbbell.howTo': 'Fique em pé segurando halteres nas laterais. Dê um passo à frente e abaixe o corpo até que ambos os joelhos formem ângulos de 90 graus. Mantenha o tronco ereto e o core engajado. Retorne à posição inicial e alterne as pernas.',
    'exercise.lyingCloseGripTricepsPress.name': 'Supino Fechado para Tríceps',
    'exercise.lyingCloseGripTricepsPress.howTo': 'Deite em um banco reto segurando uma barra com pegada estreita. Abaixe a barra em direção ao queixo dobrando os cotovelos, mantendo os braços superiores parados. Pressione a barra para cima estendendo os braços. Foque em contrair o tríceps no topo.',
    'exercise.lyingOneArmRearLateralRaise.name': 'Elevação Lateral Posterior Unilateral',
    'exercise.lyingOneArmRearLateralRaise.howTo': 'Deite de bruços em um banco inclinado, segurando um haltere em uma mão. Deixe o braço pendurado para baixo. Levante o haltere para o lado até que o braço fique paralelo ao chão. Abaixe lentamente e repita. Troque de braço após completar as repetições.',
    'exercise.lyingRearLateralRaise.name': 'Elevação Lateral Posterior Deitado',
    'exercise.lyingRearLateralRaise.howTo': 'Deite de bruços em um banco inclinado segurando halteres em ambas as mãos. Deixe os braços pendurados com as palmas voltadas uma para a outra. Levante ambos os braços para os lados até ficarem paralelos ao chão. Abaixe lentamente com controle.',
    'exercise.oneArmShoulderPress.name': 'Desenvolvimento Unilateral de Ombro',
    'exercise.oneArmShoulderPress.howTo': 'Fique em pé segurando um haltere na altura do ombro com uma mão. Pressione o peso acima da cabeça até que o braço esteja totalmente estendido. Abaixe de volta à altura do ombro com controle. Complete todas as repetições de um lado antes de trocar.',
    'exercise.oneArmTricepsExtension.name': 'Extensão de Tríceps Unilateral',
    'exercise.oneArmTricepsExtension.howTo': 'Sente-se em um banco segurando um haltere em uma mão acima da cabeça. Mantenha o braço superior parado e abaixe o peso atrás da cabeça dobrando o cotovelo. Estenda o braço de volta à posição inicial. Troque de braço após completar as repetições.',
    'exercise.oneArmUprightRow.name': 'Remada Alta Unilateral',
    'exercise.oneArmUprightRow.howTo': 'Fique em pé segurando um haltere em uma mão na coxa. Puxe o peso para cima ao longo do corpo até a altura do peito, liderando com o cotovelo. Mantenha o cotovelo mais alto que a mão durante todo o movimento. Abaixe com controle e repita.',
    'exercise.lyingTricepsExtensionAcrossFace.name': 'Extensão de Tríceps Deitado Cruzado',
    'exercise.lyingTricepsExtensionAcrossFace.howTo': 'Deite em um banco reto segurando halteres acima do peito. Abaixe os pesos em direção ao rosto dobrando os cotovelos, mantendo os braços superiores parados. Estenda de volta à posição inicial, contraindo o tríceps no topo.',
    'exercise.medicineBallBicepsCurl.name': 'Rosca com Medicine Ball na Bola de Estabilidade',
    'exercise.medicineBallBicepsCurl.howTo': 'Sente-se em uma bola de estabilidade segurando uma medicine ball com ambas as mãos. Mantenha os cotovelos nas laterais e curve a bola em direção ao peito. Abaixe lentamente com controle. A bola de estabilidade adiciona engajamento do core ao exercício.',
    'exercise.narrowGripBenchPress.name': 'Supino com Pegada Fechada',
    'exercise.narrowGripBenchPress.howTo': 'Deite em um banco reto e segure a barra com as mãos mais próximas que a largura dos ombros. Abaixe a barra até o peito inferior, mantendo os cotovelos perto do corpo. Pressione de volta à posição inicial. Isso trabalha mais o tríceps do que o supino regular.',
    'exercise.oneArmBenchPress.name': 'Supino Unilateral com Haltere',
    'exercise.oneArmBenchPress.howTo': 'Deite em um banco reto segurando um haltere em uma mão acima do peito. Abaixe o peso até a lateral do peito, depois pressione de volta para cima. Mantenha o core firme para manter o equilíbrio. Complete todas as repetições antes de trocar de braço.',
    'exercise.oneArmBicepConcentrationStabilityBall.name': 'Rosca Concentrada Unilateral na Bola de Estabilidade',
    'exercise.oneArmBicepConcentrationStabilityBall.howTo': 'Sente-se em uma bola de estabilidade com as pernas afastadas, segurando um haltere em uma mão. Apoie o cotovelo na parte interna da coxa. Curve o peso em direção ao ombro, contraindo o bíceps no topo. Abaixe lentamente e repita.',
    'exercise.oneArmPreacherCurl.name': 'Rosca Scott Unilateral',
    'exercise.oneArmPreacherCurl.howTo': 'Posicione-se em um banco Scott ou incline-se com o braço apoiado. Segure um haltere com o braço estendido. Curve o peso em direção ao ombro, focando na contração do bíceps. Abaixe com controle e repita.',
    'exercise.spiderCurl.name': 'Rosca Aranha',
    'exercise.spiderCurl.howTo': 'Deite de bruços em um banco inclinado com os braços pendurados segurando uma barra. Curve o peso em direção aos ombros mantendo os braços superiores parados. Contraia os bíceps no topo e abaixe com controle.',
    'exercise.preacherCurlBarbell.name': 'Rosca Scott com Barra',
    'exercise.preacherCurlBarbell.howTo': 'Sente-se em um banco Scott com os braços superiores apoiados no suporte. Segure uma barra com pegada supinada. Curve a barra em direção aos ombros, depois abaixe com controle. Mantenha os braços pressionados contra o suporte.',
    'exercise.pulloverStabilityBall.name': 'Pullover na Bola de Estabilidade',
    'exercise.pulloverStabilityBall.howTo': 'Deite com a parte superior das costas em uma bola de estabilidade, pés apoiados no chão. Segure um haltere com ambas as mãos acima do peito. Abaixe o peso atrás da cabeça em arco, depois puxe de volta sobre o peito. Mantenha o core engajado.',
    'exercise.pushUpFeetOnBall.name': 'Flexão com Pés na Bola de Exercício',
    'exercise.pushUpFeetOnBall.howTo': 'Coloque os pés em uma bola de estabilidade e as mãos no chão em posição de flexão. Abaixe o peito em direção ao chão dobrando os cotovelos, depois empurre de volta para cima. A superfície instável engaja o core durante todo o movimento.',
    'exercise.rearDeltoidRow.name': 'Remada para Deltoide Posterior',
    'exercise.rearDeltoidRow.howTo': 'Coloque uma mão e um joelho em um banco para apoio. Segure um haltere na outra mão com o braço estendido. Reme o peso em direção ao quadril, focando em contrair o deltoide posterior. Abaixe com controle e repita.',
    'exercise.reversePlateCurls.name': 'Rosca Invertida com Anilha',
    'exercise.reversePlateCurls.howTo': 'Fique em pé segurando uma anilha com ambas as mãos na frente das coxas, polegares para cima. Curve a anilha em direção ao peito mantendo os cotovelos nas laterais. Abaixe com controle. Isso trabalha os antebraços e bíceps.',
    'exercise.seatedTricepsPress.name': 'Tríceps Francês Sentado',
    'exercise.seatedTricepsPress.howTo': 'Sente-se em um banco segurando um haltere com ambas as mãos atrás da cabeça. Estenda os braços para pressionar o peso acima da cabeça, depois abaixe de volta atrás da cabeça. Mantenha os cotovelos próximos à cabeça durante todo o movimento.',
    'exercise.tricepDips.name': 'Mergulho de Tríceps (Banco)',
    'exercise.tricepDips.howTo': 'Sente-se na borda de um banco com as mãos segurando a borda ao lado dos quadris. Deslize os quadris para fora do banco com as pernas estendidas. Abaixe o corpo dobrando os cotovelos a cerca de 90 graus, depois empurre de volta para cima. Mantenha as costas perto do banco.',
    'exercise.parallelBarDips.name': 'Mergulho nas Barras Paralelas',
    'exercise.parallelBarDips.howTo': 'Segure as barras paralelas e levante-se com os braços totalmente estendidos. Abaixe o corpo dobrando os cotovelos até que os braços superiores fiquem paralelos ao chão. Empurre de volta à posição inicial. Mantenha o core firme durante todo o movimento.',
    'exercise.barbellSquat.name': 'Agachamento com Barra',
    'exercise.barbellSquat.howTo': 'Fique em pé com uma barra apoiada na parte superior das costas, pés na largura dos ombros. Abaixe o corpo dobrando os joelhos e quadris como se sentasse em uma cadeira. Desça até as coxas ficarem paralelas ao chão, depois suba de volta.',
    'exercise.smithMachineSquat.name': 'Agachamento no Smith Machine',
    'exercise.smithMachineSquat.howTo': 'Posicione-se sob a barra do Smith Machine com ela apoiada na parte superior das costas. Destrave a barra e abaixe o corpo dobrando os joelhos. Desça até as coxas ficarem paralelas ao chão, depois empurre de volta para cima. A máquina guia seu movimento.',
    'exercise.dumbbellSquat.name': 'Agachamento com Halteres',
    'exercise.dumbbellSquat.howTo': 'Fique em pé segurando halteres nas laterais, pés na largura dos ombros. Abaixe o corpo dobrando os joelhos e empurrando os quadris para trás. Mantenha o peito erguido e desça até as coxas ficarem paralelas ao chão, depois levante.',
    'exercise.bandSquat.name': 'Agachamento com Elástico',
    'exercise.bandSquat.howTo': 'Fique em pé sobre um elástico de resistência com os pés na largura dos ombros, segurando as alças na altura dos ombros. Abaixe em posição de agachamento, mantendo tensão no elástico. Empurre pelos calcanhares para levantar, mantendo o controle.',
    'exercise.stabilityBallCrunch.name': 'Abdominal na Bola de Estabilidade',
    'exercise.stabilityBallCrunch.howTo': 'Deite com a parte inferior das costas na bola de estabilidade, pés apoiados no chão. Coloque as mãos atrás da cabeça ou cruzadas no peito. Contraia os abdominais levantando os ombros em direção ao teto. Abaixe com controle.',
    'exercise.standingBandCurl.name': 'Rosca em Pé com Elástico',
    'exercise.standingBandCurl.howTo': 'Fique em pé sobre um elástico de resistência com os pés na largura dos ombros, segurando as alças com as palmas para cima. Mantenha os cotovelos nas laterais e curve as alças em direção aos ombros. Abaixe com controle e repita.',
    'exercise.tBarRow.name': 'Remada T-Bar',
    'exercise.tBarRow.howTo': 'Fique em pé na plataforma da remada T-bar com os pés na largura dos ombros. Incline-se para frente nos quadris e segure as alças. Puxe o peso em direção ao peito, apertando as escápulas. Abaixe com controle e repita.',
    'exercise.tricepsKickback.name': 'Coice de Tríceps',
    'exercise.tricepsKickback.howTo': 'Coloque uma mão e um joelho em um banco para apoio. Segure um haltere na outra mão com o braço superior paralelo ao chão e cotovelo dobrado a 90 graus. Estenda o braço para trás até ficar reto, contraindo o tríceps. Abaixe com controle e repita.',
    'exercise.lyingCloseGripBicepsCurls.name': 'Rosca Deitada com Pegada Fechada',
    'exercise.lyingCloseGripBicepsCurls.howTo': 'Deite em um banco reto segurando uma barra com pegada fechada. Comece com os braços estendidos acima do peito. Curve a barra em direção à testa dobrando os cotovelos, mantendo os braços superiores parados. Estenda de volta e repita.',
    'exercise.frontRaiseAndPullover.name': 'Elevação Frontal com Pullover',
    'exercise.frontRaiseAndPullover.howTo': 'Deite em um banco reto segurando uma barra com braços estendidos acima do peito. Abaixe o peso atrás da cabeça em arco, depois levante de volta e continue para frente em movimento de elevação frontal. Retorne à posição inicial.',
    'exercise.hackSquats.name': 'Agachamento Hack',
    'exercise.hackSquats.howTo': 'Posicione-se na máquina de agachamento hack com as costas contra o apoio e ombros sob os suportes. Coloque os pés na largura dos ombros na plataforma. Abaixe o corpo dobrando os joelhos, depois empurre de volta.',
    'exercise.inclineBicepsCurl.name': 'Rosca Inclinada',
    'exercise.inclineBicepsCurl.howTo': 'Sente-se em um banco inclinado segurando halteres nas laterais com braços totalmente estendidos. Curve os pesos em direção aos ombros mantendo os braços superiores parados. Abaixe com controle e repita.',
    'exercise.inclinePushdown.name': 'Pushdown Inclinado',
    'exercise.inclinePushdown.howTo': 'Sente-se em um banco inclinado de frente para uma máquina de cabo com a polia no alto. Segure a corda ou barra. Empurre o peso para baixo estendendo os cotovelos, contraindo o tríceps na parte inferior. Retorne com controle.',
    'exercise.inclineTricepsExtensionCable.name': 'Extensão de Tríceps Inclinada (Cabo)',
    'exercise.inclineTricepsExtensionCable.howTo': 'Sente-se em um banco inclinado de costas para uma polia baixa. Segure a corda atrás da cabeça com cotovelos dobrados. Estenda os braços acima da cabeça endireitando os cotovelos. Abaixe com controle.',
    'exercise.inclineTricepsExtensionBarbell.name': 'Extensão de Tríceps Inclinada (Barra)',
    'exercise.inclineTricepsExtensionBarbell.howTo': 'Deite em um banco inclinado segurando uma barra com braços estendidos acima do peito. Abaixe a barra em direção à testa dobrando os cotovelos. Estenda de volta, contraindo o tríceps no topo.',
    'exercise.jmPress.name': 'JM Press',
    'exercise.jmPress.howTo': 'Deite em um banco reto segurando uma barra com pegada fechada acima do peito. Abaixe a barra dobrando os cotovelos e trazendo-a em direção ao queixo/peito superior, combinando supino e extensão. Pressione de volta.',
    'exercise.oneArmBicepCurlOlympicBar.name': 'Rosca Unilateral com Barra Olímpica',
    'exercise.oneArmBicepCurlOlympicBar.howTo': 'Fique em pé segurando uma barra olímpica em uma extremidade com uma mão. Mantenha o cotovelo na lateral e curve a barra em direção ao ombro. Abaixe com controle e repita. Isso desenvolve força de pegada junto com os bíceps.',
    'exercise.lyingCloseGripTricepsExtensionBehindHead.name': 'Extensão de Tríceps Deitado com Pegada Fechada Atrás da Cabeça',
    'exercise.lyingCloseGripTricepsExtensionBehindHead.howTo': 'Deite em um banco reto segurando uma barra com pegada fechada. Abaixe a barra atrás da cabeça dobrando os cotovelos. Estenda os braços de volta, contraindo o tríceps no topo.',
    'exercise.lyingHighBenchBicepsCurl.name': 'Rosca Deitado em Banco Alto',
    'exercise.lyingHighBenchBicepsCurl.howTo': 'Deite de bruços em um banco alto com os braços pendurados. Segure uma barra e curve-a em direção aos ombros mantendo os braços superiores parados. Abaixe com controle.',
    'exercise.lyingInclineCurl.name': 'Rosca Deitado Inclinado',
    'exercise.lyingInclineCurl.howTo': 'Deite de bruços em um banco inclinado com os braços pendurados. Segure uma barra e curve-a em direção aos ombros. A posição inclinada proporciona um alongamento único nos bíceps.',
    'exercise.lyingSupineBicepsCurl.name': 'Rosca Supina Deitado',
    'exercise.lyingSupineBicepsCurl.howTo': 'Deite de costas em um banco reto com os braços pendurados segurando halteres. Curve os pesos em direção aos ombros mantendo os braços superiores parados. Abaixe com controle.',
    'exercise.lyingSupineTwoArmTricepsExtension.name': 'Extensão de Tríceps Supina com Dois Braços',
    'exercise.lyingSupineTwoArmTricepsExtension.howTo': 'Deite em um banco reto segurando halteres com braços estendidos acima do peito. Abaixe os pesos dobrando os cotovelos até ficarem ao lado da cabeça. Estenda de volta, contraindo o tríceps.',
    'exercise.lyingTricepsExtensionCable.name': 'Extensão de Tríceps Deitado (Cabo)',
    'exercise.lyingTricepsExtensionCable.howTo': 'Deite em um banco com a cabeça perto de uma polia baixa. Segure a corda ou barra com braços estendidos acima. Abaixe o acessório atrás da cabeça dobrando os cotovelos. Estenda de volta.',
    'exercise.lyingTricepsExtensionDumbbell.name': 'Extensão de Tríceps Deitado (Haltere)',
    'exercise.lyingTricepsExtensionDumbbell.howTo': 'Deite em um banco reto segurando um haltere com ambas as mãos acima do peito. Abaixe o peso atrás da cabeça dobrando os cotovelos. Estenda de volta, contraindo o tríceps.',
    'exercise.lyingTricepsPress.name': 'Supino para Tríceps Deitado',
    'exercise.lyingTricepsPress.howTo': 'Deite em um banco reto segurando uma barra acima do peito com braços estendidos. Abaixe a barra em direção à testa dobrando os cotovelos. Pressione de volta à posição inicial.',
    'exercise.weightedSissySquat.name': 'Agachamento Sissy com Peso',
    'exercise.weightedSissySquat.howTo': 'Fique ao lado de um poste ou suporte, segurando-o para equilíbrio com uma mão. Segure uma anilha contra o peito com a outra mão. Suba nas pontas dos pés, depois incline-se para trás enquanto dobra os joelhos para frente. Desça até que as coxas fiquem paralelas ao chão, mantendo o torso e coxas em linha reta. Empurre de volta através das pontas dos pés.',
    'exercise.thighAdductor.name': 'Adutor de Coxa',
    'exercise.thighAdductor.howTo': 'Sente-se na máquina adutora com as costas contra o apoio e pernas afastadas nos suportes. Aperte as coxas internas para trazer os suportes para dentro contra a resistência. Segure brevemente no centro, depois retorne lentamente à posição inicial com controle.',
    'exercise.standingTricepsExtension.name': 'Extensão de Tríceps em Pé',
    'exercise.standingTricepsExtension.howTo': 'Fique em pé com os pés na largura dos ombros, segurando um haltere com ambas as mãos acima da cabeça, braços totalmente estendidos. Mantenha os braços superiores próximos às orelhas e abaixe lentamente o peso atrás da cabeça dobrando os cotovelos. Estenda os braços de volta à posição inicial, contraindo o tríceps no topo.',
    'exercise.smithMachineRearDeltoidRow.name': 'Remada para Deltoide Posterior na Smith',
    'exercise.smithMachineRearDeltoidRow.howTo': 'Fique de frente para uma máquina Smith com a barra na altura das coxas. Incline-se para frente nos quadris com uma leve flexão nos joelhos. Segure a barra mais larga que os ombros com pegada pronada. Puxe a barra em direção ao peito contraindo as escápulas e levando os cotovelos para fora. Abaixe a barra com controle.',
    'exercise.seatedOverheadTricepsExtension.name': 'Extensão de Tríceps Acima da Cabeça Sentado',
    'exercise.seatedOverheadTricepsExtension.howTo': 'Sente-se em um banco com apoio para as costas, segurando uma barra acima da cabeça com braços totalmente estendidos. Mantenha os braços superiores parados e próximos à cabeça. Abaixe a barra atrás da cabeça dobrando os cotovelos. Estenda os braços de volta, contraindo o tríceps no topo.',
    'exercise.wideGripLatPullDown.name': 'Puxada Alta com Pegada Aberta',
    'exercise.wideGripLatPullDown.howTo': 'Sente-se na máquina de puxada com as coxas presas sob os apoios. Segure a barra com pegada pronada larga, mãos mais afastadas que a largura dos ombros. Puxe a barra até o peito superior enquanto contrai as escápulas. Estenda lentamente os braços de volta com controle, sentindo o alongamento nos dorsais.',
    'exercise.walkingLunges.name': 'Avanço Caminhando',
    'exercise.walkingLunges.howTo': 'Fique em pé segurando halteres nas laterais. Dê um passo à frente com uma perna e abaixe o corpo até que ambos os joelhos estejam dobrados a 90 graus. Empurre pelo calcanhar da frente e traga a perna de trás para dar o próximo passo. Continue caminhando para frente, alternando as pernas a cada passo. Mantenha o torso ereto e o core engajado.',
    'exercise.aerobics.name': 'Step Aeróbico',
    'exercise.aerobics.howTo': 'Use uma plataforma de step e siga padrões rítmicos de passos. Suba com um pé, depois o outro, e desça. Varie os movimentos com chutes, elevações de joelho e movimentos de braço. Mantenha o core engajado e um ritmo constante para benefícios cardiovasculares.',
    'exercise.mountainBiking.name': 'Mountain Bike',
    'exercise.mountainBiking.howTo': 'Pedale uma mountain bike em trilhas e terrenos acidentados. Mantenha uma postura adequada com cotovelos e joelhos levemente flexionados. Desloque o peso para trás nas descidas e para frente nas subidas. Use ambos os freios uniformemente e mantenha os olhos na trilha à frente.',
    'exercise.pilates.name': 'Pilates',
    'exercise.pilates.howTo': 'Realize movimentos controlados focando na força do core e flexibilidade. Mantenha o alinhamento e a respiração adequados durante todo o exercício. Exercícios comuns incluem o cem, roll-up e variações de prancha. Mova-se com precisão e controle ao invés de velocidade.',
    'exercise.recumbentBiking.name': 'Bicicleta Reclinada',
    'exercise.recumbentBiking.howTo': 'Sente-se em posição reclinada na bicicleta com as costas apoiadas. Ajuste o banco para que as pernas tenham uma leve flexão na extensão total. Pedale em um ritmo constante mantendo boa postura. Ótimo para cardio de baixo impacto com menos estresse nas articulações.',
    'exercise.roadCycling.name': 'Ciclismo de Estrada',
    'exercise.roadCycling.howTo': 'Pedale uma bicicleta de estrada em superfícies pavimentadas em ritmo constante. Mantenha uma posição aerodinâmica com as mãos no guidão. Pedale em movimentos circulares suaves e troque as marchas conforme o terreno. Mantenha a cadência consistente para uso eficiente de energia.',
    'exercise.rowing.name': 'Remo',
    'exercise.rowing.howTo': 'Sente-se na máquina de remo com os pés presos. Impulsione primeiro com as pernas, depois incline-se ligeiramente para trás enquanto puxa o cabo até o peito inferior. Reverta o movimento estendendo os braços, inclinando para frente e flexionando os joelhos. Mantenha o core engajado.',
    'exercise.running.name': 'Corrida',
    'exercise.running.howTo': 'Comece com uma caminhada de aquecimento, depois aumente gradualmente o ritmo para uma corrida confortável. Aterrisse no meio do pé a cada passada e mantenha os braços relaxados em ângulo de 90 graus. Respire ritmicamente e mantenha boa postura com a cabeça erguida e ombros relaxados.',
    'exercise.spinning.name': 'Spinning / Ciclismo Indoor',
    'exercise.spinning.howTo': 'Pedale uma bicicleta de spinning seguindo uma rotina de treino. Ajuste a resistência para simular subidas e sprints. Levante-se para seções de escalada e sente-se para sprints. Mantenha o core firme e uma cadência constante. Siga o instrutor ou programa para intensidade variada.',
    'exercise.stepMachine.name': 'Escada Ergométrica',
    'exercise.stepMachine.howTo': 'Fique em pé na escada ergométrica com as mãos levemente nos apoios para equilíbrio. Suba de forma controlada, empurrando pelos calcanhares. Evite apoiar-se demais nos apoios. Mantenha postura ereta e ritmo constante para cardio eficaz.',
    'exercise.swimming.name': 'Natação',
    'exercise.swimming.howTo': 'Entre na água e realize o nado escolhido com técnica adequada. No estilo livre, gire o corpo e respire para o lado. Mantenha o core engajado e as pernas chutando continuamente. Mantenha uma posição hidrodinâmica para reduzir o arrasto e melhorar a eficiência.',
    'exercise.treadmillRunning.name': 'Corrida na Esteira',
    'exercise.treadmillRunning.howTo': 'Inicie a esteira em ritmo lento de caminhada e aumente gradualmente a velocidade. Corra com uma passada natural, aterrissando no meio do pé. Use o recurso de inclinação para simular terreno externo. Mantenha a postura ereta e evite segurar nos apoios enquanto corre.',
    'exercise.walking.name': 'Caminhada Rápida',
    'exercise.walking.howTo': 'Caminhe em ritmo acelerado que eleve sua frequência cardíaca. Balance os braços naturalmente e dê passadas propositais. Mantenha a cabeça erguida e os ombros para trás. Caminhe pelo menos 30 minutos para benefícios cardiovasculares. Pode ser feito ao ar livre ou na esteira.',
    'exercise.yoga.name': 'Yoga',
    'exercise.yoga.howTo': 'Pratique várias posturas de yoga focando em flexibilidade, equilíbrio e atenção plena. Mova-se através das posturas com respiração controlada. Mantenha cada posição por várias respirações. Comece com posturas básicas e progrida para as mais avançadas conforme a flexibilidade melhora.',
    
    // Calculator page
    'calculator.hero.title': 'Calculadora de IMC',
    'calculator.hero.subtitle': 'Calcule seu Índice de Massa Corporal e entenda suas métricas de saúde',
    'calculator.title': 'Calcule Seu IMC',
    'calculator.description': 'Digite seu peso e altura para calcular seu Índice de Massa Corporal',
    'calculator.weight': 'Peso (kg)',
    'calculator.weightPlaceholder': 'Digite seu peso em kg',
    'calculator.height': 'Altura (cm)',
    'calculator.heightPlaceholder': 'Digite sua altura em cm',
    'calculator.calculate': 'Calcular IMC',
    'calculator.yourBmi': 'Seu IMC',
    'calculator.categories': 'Categorias de IMC',
    'calculator.underweight': 'Abaixo do peso',
    'calculator.normal': 'Peso normal',
    'calculator.overweight': 'Sobrepeso',
    'calculator.obese': 'Obeso',
    
    // Support Groups
    'support.title': 'Grupos de Apoio Anônimos',
    'support.subtitle': 'Conecte-se com outras pessoas, compartilhe experiências e apoiem-se mutuamente em sua jornada de saúde e bem-estar',
    'support.createTopic': 'Criar Novo Tópico',
    'support.newTopic': 'Novo Tópico de Apoio',
    'support.topicTitle': 'Título do Tópico',
    'support.description': 'Descrição',
    'support.category': 'Categoria',
    'support.create': 'Criar Tópico',
    'support.topics': 'Tópicos',
    'support.username': 'Seu nome (opcional, deixe em branco para Anônimo)',
    'support.reply': 'Compartilhe seus pensamentos...',
    'support.post': 'Postar Resposta',
    'support.selectTopic': 'Selecione um tópico para ver discussões',
    'support.success': 'Sucesso',
    'support.topicCreated': 'Tópico criado com sucesso',
    'support.deleted': 'Excluído com sucesso',
    'support.updated': 'Atualizado com sucesso',
    'support.save': 'Salvar',
    'support.cancel': 'Cancelar',
    'support.categories.mental': 'Saúde Mental',
    'support.categories.fitness': 'Exercício & Fitness',
    'support.categories.chronic': 'Condições Crônicas',
    'support.categories.wellness': 'Bem-estar Geral',
    'support.categories.sleep': 'Sono & Descanso',

    // Workout Generator
    'generator.title': 'Crie Seu Plano de Treino',
    'generator.duration': 'Duração do Treino',
    'generator.durationDesc': 'Por quanto tempo você quer treinar?',
    'generator.minutes': 'minutos',
    'generator.intensity': 'Nível de Intensidade',
    'generator.intensityDesc': 'Escolha sua intensidade preferida',
    'generator.low': 'Baixa',
    'generator.medium': 'Média',
    'generator.high': 'Alta',
    'generator.equipment': 'Equipamento Disponível',
    'generator.equipmentDesc': 'Selecione o equipamento que você tem acesso',
    'generator.generate': 'Gerar Plano de Treino',
    'generator.generating': 'Criando seu plano...',
    'generator.error': 'Erro ao gerar plano',
    'generator.tryAgain': 'Por favor, tente novamente',

    // Workout Plan View
    'plan.title': 'Seu Plano de Treino',
    'plan.noplan': 'Nenhum plano de treino ainda',
    'plan.create': 'Crie um usando o gerador',
    'plan.exercise': 'Exercício',
    'plan.sets': 'Séries',
    'plan.reps': 'Repetições',
    'plan.rest': 'Descanso',
    'plan.seconds': 'segundos',
    'plan.clear': 'Limpar Plano',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
